# Travis CI config for Listaller
# unattended full upgrade: sudo apt-get -o Dpkg::Options::="--force-confold" --force-yes -fuy dist-upgrade

language: c

compiler:
  - gcc
  - clang
before_script:
  - env | sort
  - sudo add-apt-repository "deb mirror://mirrors.ubuntu.com/mirrors.txt trusty main restricted universe multiverse" -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake intltool libarchive-dev libglib2.0-dev libgpgme11-dev
script:
  - mkdir build && cd build
  - cmake -DMAINTAINER=ON -DLIBUILD=ON ..
  - make && make test ARGS=-V && make install DESTDIR=./install_root/
