# Travis CI config for Listaller

language: c

compiler:
  - gcc
  - clang
before_script:
  - env | sort
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq && sudo DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confnew" --force-yes -fuy dist-upgrade
  - sudo apt-get install -qq cmake intltool libarchive-dev libglib2.0-dev libgpgme11-dev
script:
  - mkdir build && cd build
  - cmake -DMAINTAINER=ON -DLIBUILD=ON ..
  - make && make test ARGS=-V && make install DESTDIR=./install_root/
