# Travis CI config for Limba
# unattended full upgrade: sudo apt-get -o Dpkg::Options::="--force-confold" --force-yes -fuy dist-upgrade

language: c

compiler:
  - gcc
  - clang
before_script:
  - env | sort
  - sudo add-apt-repository "deb mirror://mirrors.ubuntu.com/US.txt trusty main restricted universe multiverse" -y
  - sudo apt-get update -qq && sudo apt-get install -qq base-files software-properties-common build-essential zlib1g # workarounds for upgrade issues
  - sudo add-apt-repository ppa:ximion/packagekit -y
  - sudo apt-get update -qq
  - sudo apt-get install cmake intltool xmlto libglib2.0-dev uuid-dev libarchive-dev libappstream-dev libgpgme11-dev gtk-doc-tools libgirepository1.0-dev libpolkit-gobject-1-dev
script:
  - mkdir build && cd build
  - cmake -DMAINTAINER=ON -DLIBUILD=ON ..
  - make && make install DESTDIR=./install_root/ && make test ARGS=-V
