# Travis CI config for Limba
# unattended full upgrade: sudo apt-get -o Dpkg::Options::="--force-confold" --force-yes -fuy dist-upgrade

language: c

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository "deb mirror://mirrors.ubuntu.com/US.txt utopic main restricted universe multiverse" -y
  - sudo apt-get update -qq

install:
  - sudo rm -f /etc/dpkg/dpkg.cfg.d/multiarch
  - sudo apt-get install -qq base-files software-properties-common build-essential zlib1g # workarounds for upgrade issues
  # GCC 4.9
  - if [ "$CC" = "gcc" ]; then sudo apt-get install -qq gcc g++; fi
  # clang 3.4
  - if [ "$CC" == "clang" ]; then sudo apt-get install -qq clang; fi

before_script:
  - env | sort
  - uname -m && uname -r
  - sudo add-apt-repository ppa:ximion/packagekit -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake intltool xmlto libglib2.0-dev uuid-dev libarchive-dev libappstream-dev libgpgme11-dev gtk-doc-tools libgirepository1.0-dev libpolkit-gobject-1-dev libcurl4-gnutls-dev

script:
  - mkdir build && cd build
  - cmake -DMAINTAINER=ON -DLIBUILD=ON ..
  - make && make install DESTDIR=./install_root/
  # tests need Linux 3.18 which Travis does not provide
  #- sudo make test ARGS=-V
